### ISSUE TITLE
Inaccurate Flesch-Kincaid Grade Level

### ISSUE THREAD

**Issue by TovlyDeutsch** [shivam5992/textstat#91] opened 2019-04-26 22:37 UTC
I'm running the function `textstat.flesch_kincaid_grade` on documents and finding extremely high grade level scores. For example the attached file ("difficult.txt") is at grade level 23.7 according to `textstat.flesch_kincaid_grade` but only at 7.6 according to other tools like https://www.webfx.com/tools/read-able/check.php. The example file is attached below.

[difficult.txt](https://github.com/shivam5992/textstat/files/3123179/difficult.txt)

**Comment by alxwrd** [comment] 2019-04-29 09:53
hi @TovlyDeutsch 👋!

Thanks for raising this issue. Have you had a look at #77? It appears to be a similar issue. Your input text is formatted in a way that textstat currently can't detect the sentence boundries.

While the issues raised previous is that there are no spaces

```plain
manage large datasets.We use this in practice
                     ^
```

your text appears to have too many spaces

```plain
         I will go into the zoo.\n         I want to see it.
    ^                                 ^
```

**Comment by TovlyDeutsch** [comment] 2019-04-30 02:06
Yeah, it does look to be a similar issue to #77. Here's NLTK's approach to sentence splitting which seems to be based on the first paper you listed in #77: https://www.nltk.org/_modules/nltk/tokenize/punkt.html#PunktSentenceTokenizer.
NLTK uses an Apache license so it may be possible to borrow liberally from that code or import it directly as a dependency (not sure if this project is avoiding introducing dependencies).

**Comment by alxwrd** [comment] 2019-06-25 16:00
I'm going to close this issue as a duplicate of #77.

**Closed by alxwrd** 2019-06-25 16:00 UTC
